name: Merge dev to stage1

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge and push
        run: |
          git checkout stage1
          git merge --no-ff dev
          git push origin stage1